# Generated by Django 4.1.5 on 2023-01-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='solapin',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
