# Generated by Django 4.1.5 on 2023-01-05 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sesion', models.CharField(max_length=255)),
                ('paridad', models.CharField(max_length=255)),
                ('dia', models.DateField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=255)),
                ('turno', models.CharField(max_length=255)),
                ('semana', models.IntegerField()),
                ('local', models.CharField(max_length=255)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardia.guardia')),
            ],
        ),
        migrations.AddField(
            model_name='guardia',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardia.horario'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
